### ISSUE TITLE
Invalid absolute import

### ISSUE THREAD

**Issue by Begi** [zenaton/examples-go#2]
Hi,

I would have been pleased to try your application but I've got a problem running `zenaton listen --env=.env --boot=./boot/boot.go` 

```shell
panic: lib/worker-0.4.5/priv/go/env-148790/scripts/replace.go:7:2:
import "/src/github.com/zenaton/examples-go/boot": cannot import absolute path


goroutine 1 [running]:
main.checkClientLibraryPath(0xc000163270, 0x4e, 0xc000018450, 0x28, 0x7ffeefbff507, 0x28)
	/Users/#####/.zenaton/lib/worker-0.4.5/priv/go/default/scripts/test_listen.go:150 +0x166
main.main()
	/Users/#####/.zenaton/lib/worker-0.4.5/priv/go/default/scripts/test_listen.go:48 +0x476
exit status 2

```

`import "/src/github.com/zenaton/examples-go/boot"`
 should be  
`import "github.com/zenaton/examples-go/boot"`

**Comment by pylebecq** [comment]
I'm closing this as this repository is now abandoned.
